// Generated by https://quicktype.io

export interface TypeProject {
    projects: Project[];
}

export interface Project {
    image:       string;
    name:        string;
    description: string;
    usedSkills:  string[];
    repo:        string;
    url:         string;
    tech:        string;
    id:         number;
}
